[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dag-viewer"
version = "0.1.0"
dependencies = [
    "zensical>=0.0.46",
]

[tool.setuptools]
py-modules = ["dag_viewer"]
packages = ["dag_viewer"]

[tool.setuptools.package-data]
dag_viewer = [
    "assets/*",
]

[tool.myapp]
system_dependencies = ["graphviz (dot binary)"]
